name: Build App
on:
    push:
        branches:
            - main
            - develop
jobs:
  build_app:
    runs-on: ubuntu-latest
    name: Build App
    steps:
    - uses: actions/checkout@v2
    - id: Build-App
      uses: ashkantaravati/NuxtToGithubPages@v1.0
      with:
        username: 'loktantra'
        reponame: 'manifesto-visualiser'
        token: ${{ secrets.GITHUB_TOKEN }}